spring:
  application:
    name: scheduler-engine
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://vrtx-pg:5435/scheduler-engine}
    username: ${SPRING_DATASOURCE_USERNAME:vrtx}
    password: ${SPRING_DATASOURCE_PASSWORD:vrtx}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
  profile:
    active: dev



server:
  port: 8081

# gRPC Configuration
grpc:
  server:
    port: 50051
    enable-reflection: true


# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.scheduler: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Scheduler settings
scheduler:
  task:
    execution-cron: "*/5 * * * * *"
    cleanup-enabled: true
    cleanup-interval: 3600000
    max-executions: 10
