server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: job
        replacement: docker
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: app
      - source_labels: ['__meta_docker_container_name']
        target_label: container_name
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
      - source_labels: ['__meta_docker_container_label_com_docker_compose_version']
        target_label: compose_version
      - source_labels: ['__meta_docker_network_name']
        target_label: docker_network
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        regex: (.*)
        replacement: /var/lib/docker/containers/$1/$1-json.log
    pipeline_stages:
      - docker: {}

