version: '3.8'

services:
  scheduler-api:
    build:
      context: ../../
      dockerfile: apps/scheduler-api/Dockerfile
    image: scheduler-api:latest
    container_name: scheduler-api
    environment:
      # MongoDB connection string
      MONGO_URI: mongodb://vrtx:vrtx@vrtx-mongodb:27017/scheduler?authSource=admin
      # Redis connection string
      REDIS_URL: redis://:vrtx@vrtx-redis:6379
      REDIS_HOST: vrtx-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: vrtx
      # JWT configuration
      JWT_SECRET: super-secret-jwt-key-change-in-production
      # gRPC configuration
      ENGINE_GRPC_URL: scheduler-engine:50051
      # Swagger documentation
      SWAGGER_USER: admin
      SWAGGER_PASS: admin123
      # Application port
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - vrtx-mongodb
      - vrtx-redis
    restart: unless-stopped

  vrtx-mongodb:
    image: mongo:5.0
    container_name: vrtx-mongodb
    environment:
      MONGO_INITDB_DATABASE: scheduler-api
      MONGO_INITDB_ROOT_USERNAME: vrtx
      MONGO_INITDB_ROOT_PASSWORD: vrtx
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped  # always restarts

  vrtx-redis:
    image: redis:7.0-alpine  # light version
    container_name: vrtx-redis
    command: ["redis-server", "--requirepass", "vrtx"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped


volumes:
  mongo-data:
  redis-data:
