global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'scheduler-engine'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['scheduler-engine:8081']

